export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_CART = "ADD_CART";
export const ADD_CART_PRODUCTS = "ADD_CART_PRODUCTS"
export const ADD_CART_PRODUCTS_FAILED = "ADD_CART_PRODUCTS_FAILED"